apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-cache
  name: redis-cache
  namespace: default
spec:
  replicas: 1
  selector:
    io.kompose.service: redis-cache
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/aero-spm-network: "true"
        io.kompose.service: redis-cache
    spec:
      containers:
        - image: ' '
          name: redis-cache
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: redis-cache-claim0
      restartPolicy: Always
      volumes:
        - name: redis-cache-claim0
          persistentVolumeClaim:
            claimName: redis-cache-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - redis-cache
        from:
          kind: ImageStreamTag
          name: redis-cache:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
